### ISSUE TITLE
Demonstrate basic N+1 solution

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq-graphql#9]
The inevitable question from anyone with a performance background is 'how do you avoid N+1s`? It's already been asked by a certain someone on the performance team (wisely), so demonstrating this using Shopify's graphql-batch or something is required.

**Comment by NickLaMuro** [comment]
> certain someone on the performance team

I wouldn't have caught this unless I was following the repo... now you have my attention...
